// Supabase Edge Function: ingest-invoice
//
// Receives parsed invoice data from the Node.js poller via HTTP POST.
// Handles: deduplication, user find-or-create, invoice insert,
// PDF upload to storage, reconciliation against approved timesheets,
// import logging.
//
// Correction rules (imported invoices only):
//   - duplicate message_id with 'success' → return duplicate, no reprocess
//   - partial/failed → delete old log, reprocess
//
// Auth: shared secret via x-ingest-secret header. JWT verification DISABLED.

import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-ingest-secret',
};

// ─── Helpers ──────────────────────────────────────────────────────────────────

function generatePassword(length = 12): string {
  const chars = 'ABCDEFGHJKMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789';
  const bytes = crypto.getRandomValues(new Uint8Array(length));
  return Array.from(bytes).map(b => chars[b % chars.length]).join('');
}

function isAutoGeneratedName(name: string | null, email: string): boolean {
  if (!name) return true;
  const prefix = email.split('@')[0].toLowerCase();
  const nameLower = name.toLowerCase().replace(/\s/g, '');
  if (nameLower === prefix) return true;
  if (!name.includes(' ')) return true;
  if (name === name.toLowerCase()) return true;
  if (name === name.toUpperCase()) return true;
  return false;
}

function looksLikeRealName(name: string | null): boolean {
  if (!name) return false;
  return name.includes(' ') && name.length > 3 && name.length < 60 && !/^\d/.test(name);
}

// ─── User management ──────────────────────────────────────────────────────────

async function findOrCreateUser(
  email: string,
  contractorName: string | null,
  supabase: ReturnType<typeof createClient>
): Promise<{ userId: string; userName: string; wasCreated: boolean; nameUpdated: boolean }> {

  const { data: existing } = await supabase
    .from('profiles')
    .select('id, name')
    .eq('email', email.toLowerCase())
    .maybeSingle();

  if (existing) {
    let nameUpdated = false;
    if (looksLikeRealName(contractorName) && isAutoGeneratedName(existing.name, email)) {
      await supabase
        .from('profiles')
        .update({ name: contractorName })
        .eq('id', existing.id);
      nameUpdated = true;
    }
    return {
      userId: existing.id,
      userName: nameUpdated ? contractorName! : (existing.name || email),
      wasCreated: false,
      nameUpdated,
    };
  }

  const guessedName = looksLikeRealName(contractorName)
    ? contractorName!
    : email.split('@')[0]
        .replace(/[._\-]/g, ' ')
        .replace(/\b\w/g, (c: string) => c.toUpperCase());

  const tempPassword = generatePassword(12);

  const { data: authUser, error: authErr } = await supabase.auth.admin.createUser({
    email: email.toLowerCase(),
    password: tempPassword,
    email_confirm: true,
  });

  if (authErr || !authUser?.user) {
    throw new Error(`Auth creation failed for ${email}: ${authErr?.message}`);
  }

  const { error: profileErr } = await supabase.from('profiles').insert({
    id:                authUser.user.id,
    email:             email.toLowerCase(),
    username:          email.toLowerCase(),
    name:              guessedName,
    role:              'timesheetuser',
    manager_id:        null,
    country:           'US',
    region:            '',
    invoice_enabled:   false,
    imported_password: tempPassword,
  });

  if (profileErr) {
    await supabase.auth.admin.deleteUser(authUser.user.id);
    throw new Error(`Profile creation failed for ${email}: ${profileErr.message}`);
  }

  return { userId: authUser.user.id, userName: guessedName, wasCreated: true, nameUpdated: false };
}

// ─── Invoice number generation ────────────────────────────────────────────────

async function generateInvoiceNumber(
  email: string,
  periodStart: string,
  supabase: ReturnType<typeof createClient>
): Promise<string> {
  const prefix = email.split('@')[0].replace(/[^a-zA-Z0-9]/g, '').toUpperCase().slice(0, 6);
  const yyyymm = periodStart.replace(/-/g, '').slice(0, 6);
  const pattern = `IMP-${prefix}-${yyyymm}-%`;

  const { count } = await supabase
    .from('invoices')
    .select('id', { count: 'exact', head: true })
    .eq('source', 'imported')
    .ilike('invoice_number', pattern);

  const seq = String((count ?? 0) + 1).padStart(2, '0');
  return `IMP-${prefix}-${yyyymm}-${seq}`;
}

// ─── Reconciliation ───────────────────────────────────────────────────────────

async function reconcile(
  userId: string,
  periodStart: string,
  periodEnd: string,
  invoiceHours: number,
  supabase: ReturnType<typeof createClient>
): Promise<{
  status: 'matched' | 'mismatch' | 'unverifiable';
  delta: number | null;
  notes: string;
}> {
  // Fetch approved timesheets that could overlap the period.
  // week_start can be up to 6 days before periodEnd and still contain days in the period.
  const rangeStart = new Date(periodStart + 'T12:00:00');
  rangeStart.setDate(rangeStart.getDate() - 6);
  const rangeStartStr = rangeStart.toISOString().slice(0, 10);

  // Status filter intentionally omitted — all submitted/pending/approved timesheets count.
  const { data: timesheets, error } = await supabase
    .from('timesheets')
    .select('entries')
    .eq('user_id', userId)
    .gte('week_start', rangeStartStr)
    .lte('week_start', periodEnd);

  if (error) {
    return { status: 'unverifiable', delta: null, notes: `DB error during reconciliation: ${error.message}` };
  }

  if (!timesheets || timesheets.length === 0) {
    return { status: 'unverifiable', delta: null, notes: 'No timesheets found for period' };
  }

  // Sum only entries whose date falls within [periodStart, periodEnd]
  let timesheetHours = 0;
  for (const ts of timesheets) {
    const entries = ts.entries as Record<string, { hours: string | number }>;
    for (const [date, entry] of Object.entries(entries)) {
      if (date >= periodStart && date <= periodEnd) {
        const h = parseFloat(String(entry.hours));
        if (!isNaN(h) && h > 0) timesheetHours += h;
      }
    }
  }

  if (timesheetHours === 0) {
    return { status: 'unverifiable', delta: null, notes: `Timesheet: 0h · Invoice: ${invoiceHours}h · Zero hours in period` };
  }

  const delta = Math.round((invoiceHours - timesheetHours) * 100) / 100;
  const matched = Math.abs(delta) < 0.01;

  return {
    status: matched ? 'matched' : 'mismatch',
    delta: matched ? 0 : delta,
    notes: `Timesheet: ${timesheetHours}h · Invoice: ${invoiceHours}h`,
  };
}

// ─── Main handler ─────────────────────────────────────────────────────────────

serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });

  // ── Auth ──────────────────────────────────────────────────────────────────
  const ingestSecret = Deno.env.get('INGEST_SECRET');
  const provided     = req.headers.get('x-ingest-secret');
  if (!ingestSecret || provided !== ingestSecret) {
    return new Response(JSON.stringify({ error: 'Unauthorized' }), {
      status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  const supabase = createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
  );

  let body: Record<string, unknown>;
  try { body = await req.json(); }
  catch {
    return new Response(JSON.stringify({ error: 'Invalid JSON' }), {
      status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  const {
    messageId,
    contractorEmail,
    contractorName,
    subject,
    attachmentName,
    // Parser output contract fields
    invoiceNumber,
    periodStart,
    periodEnd,
    totalHours,
    rate,
    totalAmount,
    currency,
    paymentDetails,
    parseNotes,
    // Raw PDF for storage upload (base64-encoded, optional)
    pdfBase64,
  } = body as Record<string, unknown>;

  if (!messageId || !contractorEmail) {
    return new Response(JSON.stringify({ error: 'Missing: messageId, contractorEmail' }), {
      status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  // ── Deduplication ─────────────────────────────────────────────────────────
  const { data: existingLog } = await supabase
    .from('email_invoice_log')
    .select('id, parse_status, attempt_count')
    .eq('message_id', messageId as string)
    .maybeSingle();

  if (existingLog) {
    const DONE_STATUSES = ['success', 'duplicate'];
    if (DONE_STATUSES.includes(existingLog.parse_status)) {
      return new Response(JSON.stringify({
        ok: true,
        action: 'duplicate',
        message: 'Already processed',
        existingStatus: existingLog.parse_status,
      }), { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
    }
    await supabase.from('email_invoice_log').delete().eq('id', existingLog.id);
  }

  const attemptCount = existingLog ? (existingLog.attempt_count || 1) + 1 : 1;

  // ── Find or create user ───────────────────────────────────────────────────
  let userId: string;
  let userName: string;
  let wasCreated: boolean;
  let nameUpdated: boolean;

  try {
    ({ userId, userName, wasCreated, nameUpdated } = await findOrCreateUser(
      contractorEmail as string,
      contractorName as string | null,
      supabase
    ));
  } catch (e) {
    await supabase.from('email_invoice_log').insert({
      message_id:     messageId,
      from_email:     contractorEmail,
      subject,
      attachment_name: attachmentName || null,
      parse_status:   'failed',
      parse_notes:    `User error: ${String(e)}`,
      attempt_count:  attemptCount,
    });
    return new Response(JSON.stringify({ ok: false, error: String(e) }), {
      status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  // ── Validate we have enough data to create an invoice ────────────────────
  const parsedPeriodStart = periodStart as string | null;
  const parsedPeriodEnd   = periodEnd   as string | null;
  const parsedHours       = totalHours  != null ? Number(totalHours) : null;
  const parsedAmount      = totalAmount != null ? Number(totalAmount) : null;

  if (!parsedPeriodStart || !parsedPeriodEnd || parsedHours === null) {
    const notes = [parseNotes, 'Insufficient data: missing period or hours'].filter(Boolean).join(' | ');
    await supabase.from('email_invoice_log').insert({
      message_id:     messageId,
      from_email:     contractorEmail,
      subject,
      attachment_name: attachmentName || null,
      parse_status:   'partial',
      parse_notes:    notes,
      user_id:        userId,
      attempt_count:  attemptCount,
    });
    return new Response(JSON.stringify({ ok: false, action: 'partial', notes }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  // ── Build invoice record ──────────────────────────────────────────────────
  let invoiceId: number | null = null;
  let parseStatus = 'success';
  let actionNotes = '';

  try {
    const parsedRate   = rate != null ? Number(rate) : 0;
    const parsedCurrency = (currency as string) || 'USD';

    // Use parsed invoice number or generate one
    const finalInvoiceNumber = (invoiceNumber as string | null)
      || await generateInvoiceNumber(contractorEmail as string, parsedPeriodStart, supabase);

    // Synthetic single line representing the full period
    const lines = [{
      weekStart:    parsedPeriodStart,
      weekEndingFri: parsedPeriodEnd,
      hours:        parsedHours,
      rate:         parsedRate,
      amount:       parsedAmount ?? parsedHours * parsedRate,
    }];

    // Build payment profile snapshot from parsed bank details (if any)
    const pd = paymentDetails as Record<string, string | null> | null;
    const paymentProfileSnapshot = pd ? {
      id:             0,
      userId,
      profileName:    'Imported',
      companyName:    pd.companyName || '',
      companyAddress: '',
      country:        '',
      bankName:       pd.bankName || '',
      bankAddress:    '',
      bankBranch:     pd.sortCode || '',
      accountNumber:  pd.accountNumber || '',
      iban:           pd.iban || '',
      swift:          pd.swift || '',
      paymentEmail:   '',
      isDefault:      false,
    } : null;

    // ── Reconcile against approved timesheets ─────────────────────────────
    const recon = await reconcile(userId, parsedPeriodStart, parsedPeriodEnd, parsedHours, supabase);

    // ── Insert invoice ────────────────────────────────────────────────────
    const { data: inserted, error: insertErr } = await supabase
      .from('invoices')
      .insert({
        user_id:                  userId,
        user_name:                userName,
        project_id:               null,
        invoice_number:           finalInvoiceNumber,
        period_start:             parsedPeriodStart,
        period_end:               parsedPeriodEnd,
        lines,
        total_hours:              parsedHours,
        rate:                     parsedRate,
        total_amount:             parsedAmount ?? parsedHours * parsedRate,
        currency:                 parsedCurrency,
        status:                   'submitted',
        submitted_at:             new Date().toISOString(),
        reviewed_at:              null,
        reviewed_by:              null,
        notes:                    '',
        payment_profile:          paymentProfileSnapshot,
        pay_on_date:              null,
        paid_date:                null,
        attachment_path:          null,
        is_vendor_invoice:        false,
        vendor_manager_id:        null,
        source:                   'imported',
        reconciliation_status:    recon.status,
        reconciliation_delta:     recon.delta,
        reconciliation_notes:     recon.notes,
      })
      .select('id')
      .single();

    if (insertErr || !inserted) {
      throw new Error(`Invoice insert failed: ${insertErr?.message}`);
    }

    invoiceId = inserted.id;
    actionNotes = `Reconciliation: ${recon.notes}`;

    // ── Upload PDF to storage ─────────────────────────────────────────────
    if (pdfBase64 && typeof pdfBase64 === 'string') {
      try {
        const pdfBytes = Uint8Array.from(atob(pdfBase64), c => c.charCodeAt(0));
        const storagePath = `${invoiceId}/original.pdf`;

        const { error: uploadErr } = await supabase.storage
          .from('invoice-attachments')
          .upload(storagePath, pdfBytes, { contentType: 'application/pdf', upsert: false });

        if (uploadErr) {
          console.warn(`PDF upload failed for invoice ${invoiceId}: ${uploadErr.message}`);
        } else {
          await supabase
            .from('invoices')
            .update({ attachment_path: storagePath })
            .eq('id', invoiceId);
        }
      } catch (uploadEx) {
        console.warn(`PDF upload exception for invoice ${invoiceId}: ${String(uploadEx)}`);
      }
    }

  } catch (e) {
    parseStatus = 'failed';
    actionNotes = `Invoice error: ${String(e)}`;
  }

  // ── Log ───────────────────────────────────────────────────────────────────
  await supabase.from('email_invoice_log').insert({
    message_id:     messageId,
    from_email:     contractorEmail,
    subject:        subject || null,
    attachment_name: attachmentName || null,
    parse_status:   parseStatus,
    parse_notes:    [parseNotes, actionNotes].filter(Boolean).join(' | '),
    user_id:        userId,
    invoice_id:     invoiceId,
    period_start:   parsedPeriodStart,
    period_end:     parsedPeriodEnd,
    raw_extracted:  body.rawExtracted ?? null,
    attempt_count:  attemptCount,
  });

  return new Response(JSON.stringify({
    ok:           parseStatus === 'success',
    action:       invoiceId ? 'created' : 'failed',
    parseStatus,
    userId,
    userName,
    wasCreated,
    nameUpdated,
    invoiceId,
    invoiceNumber: invoiceId ? undefined : null,
    periodStart:  parsedPeriodStart,
    periodEnd:    parsedPeriodEnd,
    notes:        actionNotes,
    attemptCount,
  }), { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
});
