// Supabase Edge Function: ingest-invoice
//
// Receives parsed invoice data from the Node.js poller via HTTP POST.
// Only accepts invoices forwarded by an internal accountant (forwardedBy required).
// Direct contractor submissions are rejected — accounting is the validation gate.
// Handles: forwarder gate, deduplication, user lookup (no auto-creation),
// invoice insert, PDF upload to storage, reconciliation against approved timesheets,
// import logging.
//
// Dedup rules:
//   - duplicate message_id with 'success' → return duplicate, no reprocess
//   - partial/failed → delete old log, reprocess
//
// Auth: shared secret via x-ingest-secret header. JWT verification DISABLED.

import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-ingest-secret',
};

// ─── Helpers ──────────────────────────────────────────────────────────────────

function sanitizeName(name: string | null): string | null {
  if (!name) return null;
  const cleaned = name.normalize('NFC').replace(/[\x00-\x1F\x7F-\x9F]/g, '').replace(/\s+/g, ' ').trim();
  return cleaned || null;
}

function isAutoGeneratedName(name: string | null, email: string): boolean {
  if (!name) return true;
  const prefix = email.split('@')[0].toLowerCase();
  const nameLower = name.toLowerCase().replace(/\s/g, '');
  if (nameLower === prefix) return true;
  if (!name.includes(' ')) return true;
  if (name === name.toLowerCase()) return true;
  if (name === name.toUpperCase()) return true;
  return false;
}

function looksLikeRealName(name: string | null): boolean {
  if (!name) return false;
  return name.includes(' ') && name.length > 3 && name.length < 60 && !/^\d/.test(name);
}

// ─── User management ──────────────────────────────────────────────────────────
// No auto-creation — users must be created by admin first (same policy as ingest-timesheet).

async function findUser(
  email: string,
  contractorName: string | null,
  supabase: ReturnType<typeof createClient>
): Promise<{ userId: string; userName: string; nameUpdated: boolean } | null> {

  contractorName = sanitizeName(contractorName);

  const { data: existing } = await supabase
    .from('profiles')
    .select('id, name')
    .eq('email', email.toLowerCase())
    .maybeSingle();

  if (!existing) return null;

  let nameUpdated = false;
  if (looksLikeRealName(contractorName) && isAutoGeneratedName(existing.name, email)) {
    await supabase
      .from('profiles')
      .update({ name: contractorName })
      .eq('id', existing.id);
    nameUpdated = true;
  }
  return {
    userId: existing.id,
    userName: nameUpdated ? contractorName! : (existing.name || email),
    nameUpdated,
  };
}

// ─── Invoice number generation ────────────────────────────────────────────────

async function generateInvoiceNumber(
  email: string,
  periodStart: string,
  supabase: ReturnType<typeof createClient>
): Promise<string> {
  const prefix = email.split('@')[0].replace(/[^a-zA-Z0-9]/g, '').toUpperCase().slice(0, 6);
  const yyyymm = periodStart.replace(/-/g, '').slice(0, 6);
  const pattern = `IMP-${prefix}-${yyyymm}-%`;

  const { count } = await supabase
    .from('invoices')
    .select('id', { count: 'exact', head: true })
    .eq('source', 'imported')
    .ilike('invoice_number', pattern);

  const seq = String((count ?? 0) + 1).padStart(2, '0');
  return `IMP-${prefix}-${yyyymm}-${seq}`;
}

// ─── Reconciliation ───────────────────────────────────────────────────────────

async function reconcile(
  userId: string,
  periodStart: string,
  periodEnd: string,
  invoiceHours: number,
  supabase: ReturnType<typeof createClient>
): Promise<{
  status: 'matched' | 'mismatch' | 'unverifiable';
  delta: number | null;
  notes: string;
}> {
  // Fetch approved timesheets that could overlap the period.
  // week_start can be up to 6 days before periodEnd and still contain days in the period.
  const rangeStart = new Date(periodStart + 'T12:00:00');
  rangeStart.setDate(rangeStart.getDate() - 6);
  const rangeStartStr = rangeStart.toISOString().slice(0, 10);

  // Status filter intentionally omitted — all submitted/pending/approved timesheets count.
  const { data: timesheets, error } = await supabase
    .from('timesheets')
    .select('entries')
    .eq('user_id', userId)
    .gte('week_start', rangeStartStr)
    .lte('week_start', periodEnd);

  if (error) {
    return { status: 'unverifiable', delta: null, notes: `DB error during reconciliation: ${error.message}` };
  }

  if (!timesheets || timesheets.length === 0) {
    return { status: 'unverifiable', delta: null, notes: 'No timesheets found for period' };
  }

  // Sum only entries whose date falls within [periodStart, periodEnd]
  let timesheetHours = 0;
  for (const ts of timesheets) {
    const entries = ts.entries as Record<string, { hours: string | number }>;
    for (const [date, entry] of Object.entries(entries)) {
      if (date >= periodStart && date <= periodEnd) {
        const h = parseFloat(String(entry.hours));
        if (!isNaN(h) && h > 0) timesheetHours += h;
      }
    }
  }

  if (timesheetHours === 0) {
    return { status: 'unverifiable', delta: null, notes: `Timesheet: 0h · Invoice: ${invoiceHours}h · Zero hours in period` };
  }

  const delta = Math.round((invoiceHours - timesheetHours) * 100) / 100;
  const matched = Math.abs(delta) < 0.01;

  return {
    status: matched ? 'matched' : 'mismatch',
    delta: matched ? 0 : delta,
    notes: `Timesheet: ${timesheetHours}h · Invoice: ${invoiceHours}h`,
  };
}

// ─── Main handler ─────────────────────────────────────────────────────────────

serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });

  // ── Auth ──────────────────────────────────────────────────────────────────
  const ingestSecret = Deno.env.get('INGEST_SECRET');
  const provided     = req.headers.get('x-ingest-secret');
  if (!ingestSecret || provided !== ingestSecret) {
    return new Response(JSON.stringify({ error: 'Unauthorized' }), {
      status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  const supabase = createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
  );

  let body: Record<string, unknown>;
  try { body = await req.json(); }
  catch {
    return new Response(JSON.stringify({ error: 'Invalid JSON' }), {
      status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  const {
    messageId,
    contractorEmail,
    contractorName,
    subject,
    attachmentName,
    forwardedBy,
    // Parser output contract fields
    invoiceNumber,
    periodStart,
    periodEnd,
    totalHours,
    rate,
    totalAmount,
    currency,
    paymentDetails,
    parseNotes,
    // Raw PDF for storage upload (base64-encoded, optional)
    pdfBase64,
    // Multi-contractor grouping key (set for grouped invoices; null for single)
    groupKey,
    // True when subject/body contains correction keywords ("fixed", "revised", etc.)
    correctionHint,
    // SHA-256 hex digest of the attachment bytes (for dedup analytics)
    attachmentHash,
  } = body as Record<string, unknown>;

  if (!messageId || !contractorEmail) {
    return new Response(JSON.stringify({ error: 'Missing: messageId, contractorEmail' }), {
      status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  // Only accept invoices forwarded by an internal accountant.
  // Direct contractor submissions are rejected — accounting reviews before the system ingests.
  if (!forwardedBy) {
    await supabase.from('email_invoice_log').insert({
      message_id:      messageId,
      from_email:      contractorEmail,
      subject:         subject || null,
      attachment_name: attachmentName || null,
      parse_status:    'failed',
      parse_notes:     'Direct invoice submission not accepted — must be forwarded by an internal accountant',
    });
    return new Response(JSON.stringify({ ok: false, error: 'direct_invoice_not_accepted' }), {
      status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  // ── Deduplication ─────────────────────────────────────────────────────────
  const { data: existingLog } = await supabase
    .from('email_invoice_log')
    .select('id, parse_status, attempt_count')
    .eq('message_id', messageId as string)
    .maybeSingle();

  if (existingLog) {
    const DONE_STATUSES = ['success', 'duplicate'];
    if (DONE_STATUSES.includes(existingLog.parse_status)) {
      return new Response(JSON.stringify({
        ok: true,
        action: 'duplicate',
        message: 'Already processed',
        existingStatus: existingLog.parse_status,
      }), { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
    }
    await supabase.from('email_invoice_log').delete().eq('id', existingLog.id);
  }

  const attemptCount = existingLog ? (existingLog.attempt_count || 1) + 1 : 1;

  // ── Find user (no auto-creation) ─────────────────────────────────────────
  let userId: string;
  let userName: string;
  let nameUpdated: boolean;

  try {
    const found = await findUser(
      contractorEmail as string,
      contractorName as string | null,
      supabase
    );
    if (!found) {
      await supabase.from('email_invoice_log').insert({
        message_id:      messageId,
        from_email:      contractorEmail,
        subject:         subject || null,
        attachment_name: attachmentName || null,
        parse_status:    'failed',
        parse_notes:     'Unknown contractor — not in profiles. Add user via admin panel first.',
        attempt_count:   attemptCount,
      });
      return new Response(JSON.stringify({ ok: false, error: 'unknown_contractor' }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }
    ({ userId, userName, nameUpdated } = found);
  } catch (e) {
    await supabase.from('email_invoice_log').insert({
      message_id:      messageId,
      from_email:      contractorEmail,
      subject:         subject || null,
      attachment_name: attachmentName || null,
      parse_status:    'failed',
      parse_notes:     `User lookup error: ${String(e)}`,
      attempt_count:   attemptCount,
    });
    return new Response(JSON.stringify({ ok: false, error: String(e) }), {
      status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  // ── Validate we have enough data to create an invoice ────────────────────
  const parsedPeriodStart = periodStart as string | null;
  const parsedPeriodEnd   = periodEnd   as string | null;
  let   parsedHours       = totalHours  != null ? Number(totalHours) : null;
  const parsedAmount      = totalAmount != null ? Number(totalAmount) : null;

  if (parsedPeriodEnd && new Date(parsedPeriodEnd + 'T12:00:00Z').getTime() > Date.now()) {
    const notes = [parseNotes, `Billing period end ${parsedPeriodEnd} is in the future — likely parse error`].filter(Boolean).join(' | ');
    await supabase.from('email_invoice_log').insert({
      message_id: messageId, from_email: contractorEmail, subject,
      attachment_name: attachmentName || null, parse_status: 'partial', parse_notes: notes,
      user_id: userId, attempt_count: attemptCount,
    });
    return new Response(JSON.stringify({ ok: false, action: 'partial', notes }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  if (!parsedPeriodStart || !parsedPeriodEnd) {
    const notes = [parseNotes, 'Insufficient data: billing period not found'].filter(Boolean).join(' | ');
    await supabase.from('email_invoice_log').insert({
      message_id:     messageId,
      from_email:     contractorEmail,
      subject,
      attachment_name: attachmentName || null,
      parse_status:   'partial',
      parse_notes:    notes,
      user_id:        userId,
      attempt_count:  attemptCount,
    });
    return new Response(JSON.stringify({ ok: false, action: 'partial', notes }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  // ── Derive hours from timesheets if invoice has none ─────────────────────
  let hoursSourceNote: string | null = null;
  if (parsedHours == null) {
    const rangeStart = new Date(parsedPeriodStart + 'T12:00:00');
    rangeStart.setDate(rangeStart.getDate() - 6);
    const { data: tss } = await supabase
      .from('timesheets')
      .select('entries')
      .eq('user_id', userId)
      .gte('week_start', rangeStart.toISOString().slice(0, 10))
      .lte('week_start', parsedPeriodEnd);
    if (tss && tss.length > 0) {
      let tsHours = 0;
      for (const ts of tss) {
        const entries = ts.entries as Record<string, { hours: string | number }>;
        for (const [date, entry] of Object.entries(entries)) {
          if (date >= parsedPeriodStart && date <= parsedPeriodEnd) {
            const h = parseFloat(String(entry.hours));
            if (!isNaN(h) && h > 0) tsHours += h;
          }
        }
      }
      if (tsHours > 0) {
        parsedHours = Math.round(tsHours * 100) / 100;
        hoursSourceNote = `Hours derived from timesheets (${parsedHours}h) — not on invoice`;
      }
    }
  }

  // ── Build invoice record ──────────────────────────────────────────────────
  let invoiceId: number | null = null;
  let parseStatus = 'success';
  let actionNotes = '';
  let reconStatus: 'matched' | 'mismatch' | 'unverifiable' | null = null;
  let reconDelta: number | null = null;
  let resolvedInvoiceNumber: string | null = null;

  try {
    const parsedRate     = rate != null ? Number(rate) : null;
    const parsedCurrency = (currency as string) || 'USD';

    // Use parsed invoice number or generate one
    const finalInvoiceNumber = (invoiceNumber as string | null)
      || await generateInvoiceNumber(contractorEmail as string, parsedPeriodStart, supabase);
    resolvedInvoiceNumber = finalInvoiceNumber;

    // Synthetic single line representing the full period.
    // hours/rate may be null for amount-only invoices (no hourly breakdown).
    const computedAmount = parsedAmount
      ?? (parsedHours != null && parsedRate != null ? parsedHours * parsedRate : 0);
    const lines = [{
      weekStart:     parsedPeriodStart,
      weekEndingFri: parsedPeriodEnd,
      hours:         parsedHours,
      rate:          parsedRate,
      amount:        computedAmount,
    }];

    // Build payment profile snapshot from parsed bank details (if any)
    const pd = paymentDetails as Record<string, string | null> | null;
    let paymentProfileSnapshot = pd ? {
      id:             0,
      userId,
      profileName:    'Imported',
      companyName:    pd.companyName || '',
      companyAddress: '',
      country:        '',
      bankName:       pd.bankName || '',
      bankAddress:    '',
      bankBranch:     pd.sortCode || '',
      accountNumber:  pd.accountNumber || '',
      iban:           pd.iban || '',
      swift:          pd.swift || '',
      paymentEmail:   '',
      isDefault:      false,
    } : null;

    // ── Resolve payment profile via Convera beneficiary lookup ───────────────
    // Source of truth: convera_beneficiaries (verified bank data from Convera exports).
    // Flow:
    //   1. Incomplete parsed data (no IBAN / no SWIFT+account) → strip; accountant assigns.
    //   2. Already-linked existing payment_profile (same user, matching IBAN/swift+acc) → reuse.
    //   3. Lookup convera_beneficiaries by IBAN. If 1 match → hydrate. If multiple (shared
    //      intermediary like Bimosoft/NativeTeams/Revolut) → narrow by short_name containing
    //      contractor's name. Create payment_profile linked to the beneficiary.
    //   4. No beneficiary match → create a "pending" payment_profile from parsed data; it
    //      will be enriched when a future Convera CSV import creates the matching beneficiary.
    if (pd && paymentProfileSnapshot) {
      const norm = (s: string | null | undefined) => (s || '').toUpperCase().replace(/\s+/g, '').trim();
      const unaccent = (s: string) => s.normalize('NFD').replace(/[̀-ͯ]/g, '');
      const ibanN  = norm(pd.iban);
      const swiftN = norm(pd.swift);
      const accN   = norm(pd.accountNumber);

      const hasIban   = !!ibanN;
      const hasSwAcc  = !!(swiftN && accN);

      if (!hasIban && !hasSwAcc) {
        // Step 1 — incomplete
        paymentProfileSnapshot = null;
      } else {
        // Step 2 — user's existing profiles
        const { data: existing } = await supabase
          .from('payment_profiles')
          .select('id, profile_name, company_name, company_address, country, bank_name, bank_address, bank_branch, account_number, iban, swift, payment_email, is_default, convera_beneficiary_id')
          .eq('user_id', userId);

        const buildSnapshot = (row: Record<string, unknown>) => ({
          id:             row.id as number,
          userId,
          profileName:    (row.profile_name as string) || 'Imported',
          companyName:    (row.company_name as string) || '',
          companyAddress: (row.company_address as string) || '',
          country:        (row.country as string) || '',
          bankName:       (row.bank_name as string) || '',
          bankAddress:    (row.bank_address as string) || '',
          bankBranch:     (row.bank_branch as string) || '',
          accountNumber:  (row.account_number as string) || '',
          iban:           (row.iban as string) || '',
          swift:          (row.swift as string) || '',
          paymentEmail:   (row.payment_email as string) || '',
          isDefault:      Boolean(row.is_default),
        });

        let resolved = false;

        const existingMatch = hasIban
          ? (existing ?? []).find(p => norm(p.iban) === ibanN)
          : (existing ?? []).find(p => norm(p.swift) === swiftN && norm(p.account_number) === accN);
        if (existingMatch) {
          paymentProfileSnapshot = buildSnapshot(existingMatch);
          resolved = true;
        }

        // Step 3 — Convera beneficiary lookup. NOTE: convera_beneficiaries.bank_account
        // holds the IBAN (for non-US) or the account number (for US). iban_unique is a
        // BOOLEAN flag (true = unique to this beneficiary, false = shared intermediary like
        // Revolut/Bimosoft). We match the parsed IBAN against bank_account.
        if (!resolved && hasIban) {
          const { data: benefs } = await supabase
            .from('convera_beneficiaries')
            .select('id, short_name, beneficiary_name, beneficiary_country, bank_name, bank_account, iban_unique')
            .ilike('bank_account', ibanN);

          let chosen: Record<string, unknown> | null = null;
          if (benefs && benefs.length === 1) {
            chosen = benefs[0];
          } else if (benefs && benefs.length > 1) {
            // Shared intermediary — disambiguate by user name in short_name
            const userTokens = unaccent((userName as string).toLowerCase())
              .split(/\s+/).filter(t => t.length >= 3);
            chosen = benefs.find(b => {
              const sn = unaccent(((b.short_name as string) || '').toLowerCase());
              return userTokens.some(t => sn.includes(t));
            }) ?? null;
          }

          if (chosen) {
            const alreadyLinked = (existing ?? []).find(p => p.convera_beneficiary_id === chosen!.id);
            if (alreadyLinked) {
              paymentProfileSnapshot = buildSnapshot(alreadyLinked);
              resolved = true;
            } else {
              // bank_account holds IBAN if it starts with 2-letter country code; else account number
              const benefAccount = (chosen.bank_account as string) || '';
              const isIbanFormat = /^[A-Z]{2}\d/.test(benefAccount.replace(/\s+/g, '').toUpperCase());
              // INSERT new payment_profile hydrated from the beneficiary
              const { data: inserted } = await supabase
                .from('payment_profiles')
                .insert({
                  user_id:                userId,
                  profile_name:           (chosen.short_name as string) || 'Imported',
                  company_name:           (chosen.beneficiary_name as string) || pd.companyName || '',
                  country:                (chosen.beneficiary_country as string) || '',
                  bank_name:              (chosen.bank_name as string) || pd.bankName || '',
                  bank_branch:            pd.sortCode || '',
                  account_number:         isIbanFormat ? (pd.accountNumber || '') : (benefAccount || pd.accountNumber || ''),
                  iban:                   isIbanFormat ? benefAccount : (pd.iban || ''),
                  swift:                  pd.swift || '',
                  convera_beneficiary_id: chosen.id,
                  is_default:             false,
                })
                .select('id, profile_name, company_name, company_address, country, bank_name, bank_address, bank_branch, account_number, iban, swift, payment_email, is_default')
                .single();
              if (inserted) {
                paymentProfileSnapshot = buildSnapshot(inserted);
                resolved = true;
              }
            }
          }
        }

        // Step 3.5 — Name-based beneficiary fallback (requires BOTH first and last name
        // as substring in short_name or beneficiary_name). Skips spelling variants by design;
        // accountant handles those manually (one-time link).
        if (!resolved) {
          const parts = unaccent((userName as string).toLowerCase()).split(/\s+/).filter(t => t.length >= 3);
          if (parts.length >= 2) {
            const first = parts[0];
            const last = parts[parts.length - 1];
            const { data: nameBenefs } = await supabase
              .from('convera_beneficiaries')
              .select('id, short_name, beneficiary_name, beneficiary_country, bank_name, bank_account, iban_unique')
              .or(`short_name.ilike.*${last}*,beneficiary_name.ilike.*${last}*`);
            const nameMatches = (nameBenefs ?? []).filter(b => {
              const sn = unaccent(((b.short_name as string) || '').toLowerCase());
              const bn = unaccent(((b.beneficiary_name as string) || '').toLowerCase());
              return (sn.includes(first) && sn.includes(last)) || (bn.includes(first) && bn.includes(last));
            });
            if (nameMatches.length === 1) {
              const m = nameMatches[0];
              const alreadyLinked = (existing ?? []).find(p => p.convera_beneficiary_id === m.id);
              if (alreadyLinked) {
                paymentProfileSnapshot = buildSnapshot(alreadyLinked);
                resolved = true;
              } else {
                const benefAccount = (m.bank_account as string) || '';
                const isIbanFormat = /^[A-Z]{2}\d/.test(benefAccount.replace(/\s+/g, '').toUpperCase());
                const { data: inserted } = await supabase
                  .from('payment_profiles')
                  .insert({
                    user_id:                userId,
                    profile_name:           (m.short_name as string) || 'Imported',
                    company_name:           (m.beneficiary_name as string) || pd.companyName || '',
                    country:                (m.beneficiary_country as string) || '',
                    bank_name:              (m.bank_name as string) || pd.bankName || '',
                    bank_branch:            pd.sortCode || '',
                    account_number:         isIbanFormat ? (pd.accountNumber || '') : (benefAccount || pd.accountNumber || ''),
                    iban:                   isIbanFormat ? benefAccount : (pd.iban || ''),
                    swift:                  pd.swift || '',
                    convera_beneficiary_id: m.id,
                    is_default:             false,
                  })
                  .select('id, profile_name, company_name, company_address, country, bank_name, bank_address, bank_branch, account_number, iban, swift, payment_email, is_default')
                  .single();
                if (inserted) { paymentProfileSnapshot = buildSnapshot(inserted); resolved = true; }
              }
            }
            // If 0 or >1 name matches, fall through to last-used / pending
          }
        }

        // Step 3.6 — Last-used profile fallback. When neither IBAN nor name matched,
        // pull the contractor's most recent prior invoice's payment_profile if it has
        // usable bank data. This is the "they've been paid this way before" signal.
        if (!resolved) {
          const { data: priorInvoices } = await supabase
            .from('invoices')
            .select('payment_profile')
            .eq('user_id', userId)
            .lt('period_start', parsedPeriodStart)
            .not('payment_profile', 'is', null)
            .order('period_start', { ascending: false })
            .limit(5);
          const usefulPrior = (priorInvoices ?? [])
            .map(r => r.payment_profile as Record<string, unknown> | null)
            .find(pp => pp && (pp.iban || pp.accountNumber));
          if (usefulPrior) {
            // Use prior snapshot directly; this is just the JSONB carried over
            paymentProfileSnapshot = { ...paymentProfileSnapshot, ...usefulPrior, userId } as typeof paymentProfileSnapshot;
            resolved = true;
          }
        }

        // Step 4 — no beneficiary match, persist a "pending" profile from parsed data
        if (!resolved) {
          const monthNames = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
          const [pyear, pmonth] = parsedPeriodStart.split('-');
          const periodLabel = `${monthNames[parseInt(pmonth) - 1]} ${pyear}`;
          const { data: inserted } = await supabase
            .from('payment_profiles')
            .insert({
              user_id:         userId,
              profile_name:    `Imported ${periodLabel}`,
              company_name:    pd.companyName || '',
              country:         '',
              bank_name:       pd.bankName || '',
              bank_branch:     pd.sortCode || '',
              account_number:  pd.accountNumber || '',
              iban:            pd.iban || '',
              swift:           pd.swift || '',
              is_default:      false,
            })
            .select('id, profile_name, company_name, company_address, country, bank_name, bank_address, bank_branch, account_number, iban, swift, payment_email, is_default')
            .single();
          if (inserted) paymentProfileSnapshot = buildSnapshot(inserted);
          // If insert failed, fall through with original in-memory snapshot (id=0, name 'Imported')
        }
      }
    }

    // ── Check for existing invoice for same user + period ────────────────────
    // True duplicate → reattach PDF only, no data changes.
    // Correction (fields differ) → update data, reset to submitted, mark corrected.
    const { data: existingInvoice } = await supabase
      .from('invoices')
      .select('id, attachment_path, total_hours, rate, total_amount, status')
      .eq('user_id', userId)
      .eq('period_start', parsedPeriodStart)
      .eq('period_end', parsedPeriodEnd)
      .eq('source', 'imported')
      .maybeSingle();

    if (existingInvoice) {
      invoiceId = existingInvoice.id;

      const existingHours  = existingInvoice.total_hours  != null ? Number(existingInvoice.total_hours)  : null;
      const existingRate   = existingInvoice.rate          != null ? Number(existingInvoice.rate)          : null;
      const existingAmount = existingInvoice.total_amount  != null ? Number(existingInvoice.total_amount)  : null;
      const isDuplicate    = !correctionHint
                          && existingHours === parsedHours
                          && existingRate  === parsedRate
                          && Math.abs((existingAmount ?? 0) - computedAmount) < 0.01;

      if (!isDuplicate) {
        // Correction: update invoice data and reset status for re-approval.
        // invoice_number must be updated too — corrected PDFs often have a new number
        // and the audit trail lives in email_invoice_log.raw_extracted snapshots.
        const updatePayload: Record<string, unknown> = {
          invoice_number: finalInvoiceNumber,
          total_hours:    parsedHours,
          rate:           parsedRate,
          total_amount:   computedAmount,
          lines,
          corrected:      true,
          status:         'submitted',
          reviewed_at:    null,
          reviewed_by:    null,
        };
        if (paymentProfileSnapshot) updatePayload.payment_profile = paymentProfileSnapshot;

        await supabase.from('invoices').update(updatePayload).eq('id', invoiceId);

        // Upload replacement PDF if provided
        if (pdfBase64 && typeof pdfBase64 === 'string') {
          try {
            const attName2  = (attachmentName as string) || '';
            const extM2     = attName2.match(/\.([a-zA-Z0-9]+)$/);
            const ext2      = extM2 ? extM2[1].toLowerCase() : 'pdf';
            const mimeMap2: Record<string, string> = { pdf: 'application/pdf', docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', doc: 'application/msword' };
            const sp2 = `${invoiceId}/original.${ext2}`;
            const { error: upErr2 } = await supabase.storage
              .from('invoice-attachments')
              .upload(sp2, Uint8Array.from(atob(pdfBase64 as string), c => c.charCodeAt(0)),
                { contentType: mimeMap2[ext2] || 'application/octet-stream', upsert: true });
            if (!upErr2) await supabase.from('invoices').update({ attachment_path: sp2 }).eq('id', invoiceId);
          } catch {}
        }

        actionNotes = `Corrected invoice (id=${invoiceId}): hours ${existingHours}→${parsedHours}, rate ${existingRate}→${parsedRate}, amount ${existingAmount}→${computedAmount}`;
        await supabase.from('email_invoice_log').insert({
          message_id:      messageId,
          from_email:      contractorEmail,
          subject:         subject || null,
          attachment_name: attachmentName || null,
          parse_status:    'success',
          parse_notes:     [parseNotes, hoursSourceNote, actionNotes].filter(Boolean).join(' | '),
          user_id:         userId,
          invoice_id:      invoiceId,
          period_start:    parsedPeriodStart,
          period_end:      parsedPeriodEnd,
          raw_extracted:   body.rawExtracted ?? null,
          attempt_count:   attemptCount,
          attachment_hash: (attachmentHash as string) || null,
        });
        return new Response(JSON.stringify({
          ok: true, action: 'corrected', parseStatus: 'success',
          userId, userName, invoiceId, invoiceNumber: resolvedInvoiceNumber,
          periodStart: parsedPeriodStart, periodEnd: parsedPeriodEnd, notes: actionNotes,
        }), { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
      }

      // True duplicate — reattach PDF only
      actionNotes = existingInvoice.attachment_path
        ? `Invoice already exists (id=${invoiceId}) with attachment — skipped`
        : `Invoice already exists (id=${invoiceId}) — attaching PDF only`;

      if (!existingInvoice.attachment_path && pdfBase64 && typeof pdfBase64 === 'string') {
        const attName2 = (attachmentName as string) || '';
        const extM2    = attName2.match(/\.([a-zA-Z0-9]+)$/);
        const ext2     = extM2 ? extM2[1].toLowerCase() : 'pdf';
        const mimeMap2: Record<string, string> = { pdf: 'application/pdf', docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', doc: 'application/msword', msg: 'application/vnd.ms-outlook' };
        const sp2 = `${invoiceId}/original.${ext2}`;
        const { error: upErr } = await supabase.storage
          .from('invoice-attachments')
          .upload(sp2, Uint8Array.from(atob(pdfBase64), c => c.charCodeAt(0)),
            { contentType: mimeMap2[ext2] || 'application/octet-stream', upsert: true });
        if (!upErr) {
          await supabase.from('invoices').update({ attachment_path: sp2 }).eq('id', invoiceId);
          actionNotes = `Re-attached PDF to existing invoice (id=${invoiceId})`;
        } else {
          actionNotes += ` | PDF upload failed: ${upErr.message}`;
        }
      }

      await supabase.from('email_invoice_log').insert({
        message_id:      messageId,
        from_email:      contractorEmail,
        subject:         subject || null,
        attachment_name: attachmentName || null,
        parse_status:    'duplicate',
        parse_notes:     actionNotes,
        user_id:         userId,
        invoice_id:      invoiceId,
        period_start:    parsedPeriodStart,
        period_end:      parsedPeriodEnd,
        attempt_count:   attemptCount,
        attachment_hash: (attachmentHash as string) || null,
      });

      return new Response(JSON.stringify({
        ok: true, action: 'reattached', parseStatus: 'duplicate',
        userId, userName, invoiceId, periodStart: parsedPeriodStart, notes: actionNotes,
      }), { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
    }

    // ── Reconcile against approved timesheets (skip for amount-only invoices) ──
    const recon = parsedHours != null
      ? await reconcile(userId, parsedPeriodStart, parsedPeriodEnd, parsedHours, supabase)
      : { status: 'unverifiable' as const, delta: null, notes: 'No hours on invoice — amount-only, cannot reconcile' };

    // ── Insert invoice ────────────────────────────────────────────────────
    const { data: inserted, error: insertErr } = await supabase
      .from('invoices')
      .insert({
        user_id:                  userId,
        user_name:                userName,
        project_id:               null,
        invoice_number:           finalInvoiceNumber,
        period_start:             parsedPeriodStart,
        period_end:               parsedPeriodEnd,
        lines,
        total_hours:              parsedHours,
        rate:                     parsedRate,
        total_amount:             computedAmount,
        currency:                 parsedCurrency,
        status:                   'submitted',
        submitted_at:             new Date().toISOString(),
        reviewed_at:              null,
        reviewed_by:              null,
        notes:                    '',
        payment_profile:          paymentProfileSnapshot,
        pay_on_date:              null,
        paid_date:                null,
        attachment_path:          null,
        is_vendor_invoice:        false,
        vendor_manager_id:        null,
        source:                   'imported',
        reconciliation_status:    recon.status,
        reconciliation_delta:     recon.delta,
        reconciliation_notes:     recon.notes,
        group_key:                (groupKey as string | null) || null,
      })
      .select('id')
      .single();

    if (insertErr || !inserted) {
      throw new Error(`Invoice insert failed: ${insertErr?.message}`);
    }

    invoiceId = inserted.id;
    reconStatus = recon.status;
    reconDelta  = recon.delta;
    actionNotes = `Reconciliation: ${recon.notes}`;

    // ── Upload attachment to storage ──────────────────────────────────────
    if (pdfBase64 && typeof pdfBase64 === 'string') {
      try {
        const attBytes = Uint8Array.from(atob(pdfBase64), c => c.charCodeAt(0));
        const attName = (attachmentName as string) || '';
        const extMatch = attName.match(/\.([a-zA-Z0-9]+)$/);
        const ext = extMatch ? extMatch[1].toLowerCase() : 'pdf';
        const mimeMap: Record<string, string> = {
          pdf:  'application/pdf',
          docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
          doc:  'application/msword',
          msg:  'application/vnd.ms-outlook',
        };
        const contentType = mimeMap[ext] || 'application/octet-stream';
        const storagePath = `${invoiceId}/original.${ext}`;

        const { error: uploadErr } = await supabase.storage
          .from('invoice-attachments')
          .upload(storagePath, attBytes, { contentType, upsert: false });

        if (uploadErr) {
          console.warn(`Attachment upload failed for invoice ${invoiceId}: ${uploadErr.message}`);
        } else {
          await supabase
            .from('invoices')
            .update({ attachment_path: storagePath })
            .eq('id', invoiceId);
        }
      } catch (uploadEx) {
        console.warn(`Attachment upload exception for invoice ${invoiceId}: ${String(uploadEx)}`);
      }
    }

  } catch (e) {
    parseStatus = 'failed';
    actionNotes = `Invoice error: ${String(e)}`;
  }

  // ── Log ───────────────────────────────────────────────────────────────────
  await supabase.from('email_invoice_log').insert({
    message_id:      messageId,
    from_email:      contractorEmail,
    subject:         subject || null,
    attachment_name: attachmentName || null,
    parse_status:    parseStatus,
    parse_notes:     [parseNotes, hoursSourceNote, actionNotes].filter(Boolean).join(' | '),
    user_id:         userId,
    invoice_id:      invoiceId,
    period_start:    parsedPeriodStart,
    period_end:      parsedPeriodEnd,
    raw_extracted:   body.rawExtracted ?? null,
    attempt_count:   attemptCount,
    attachment_hash: (attachmentHash as string) || null,
  });

  return new Response(JSON.stringify({
    ok:                  parseStatus === 'success',
    action:              invoiceId ? 'created' : 'failed',
    parseStatus,
    userId,
    userName,
    nameUpdated,
    invoiceId,
    invoiceNumber:       resolvedInvoiceNumber,
    periodStart:         parsedPeriodStart,
    periodEnd:           parsedPeriodEnd,
    forwardedBy:         forwardedBy || null,
    reconciliationStatus: reconStatus,
    reconciliationDelta:  reconDelta,
    notes:               actionNotes,
    attemptCount,
  }), { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
});
