// Supabase Edge Function: ingest-timesheet
//
// Receives parsed timesheet data from the Node.js poller via HTTP POST.
// Handles: deduplication, user find-or-create, name improvement,
// timesheet upsert, correction detection, import logging.
//
// Correction rules:
//   - source='direct' exists → never overwrite, log as correction_pending
//   - source='imported' exists → update hours, set status='pending' for review
//   - no existing record → create as approved (auto-approved on import)
//
// Auth: shared secret via x-ingest-secret header. JWT verification DISABLED.

import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-ingest-secret',
};

// ─── Helpers ──────────────────────────────────────────────────────────────────

function generatePassword(length = 12): string {
  const chars = 'ABCDEFGHJKMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789';
  const bytes = crypto.getRandomValues(new Uint8Array(length));
  return Array.from(bytes).map(b => chars[b % chars.length]).join('');
}

// Detect if a stored name looks auto-generated from email prefix (worth replacing)
function isAutoGeneratedName(name: string | null, email: string): boolean {
  if (!name) return true;
  const prefix = email.split('@')[0].toLowerCase();
  const nameLower = name.toLowerCase().replace(/\s/g, '');
  if (nameLower === prefix) return true;           // exact email prefix match
  if (!name.includes(' ')) return true;            // single word = likely auto-generated
  if (name === name.toLowerCase()) return true;    // all lowercase
  if (name === name.toUpperCase()) return true;    // all uppercase
  return false;
}

function looksLikeRealName(name: string | null): boolean {
  if (!name) return false;
  return name.includes(' ') && name.length > 3 && name.length < 60 && !/^\d/.test(name);
}

// ─── User management ──────────────────────────────────────────────────────────

async function findOrCreateUser(
  email: string,
  contractorName: string | null,
  supabase: ReturnType<typeof createClient>
): Promise<{ userId: string; userName: string; wasCreated: boolean; nameUpdated: boolean }> {

  const { data: existing } = await supabase
    .from('profiles')
    .select('id, name')
    .eq('email', email.toLowerCase())
    .maybeSingle();

  if (existing) {
    let nameUpdated = false;
    // Update name if existing looks auto-generated and we have a better one
    if (looksLikeRealName(contractorName) && isAutoGeneratedName(existing.name, email)) {
      await supabase
        .from('profiles')
        .update({ name: contractorName })
        .eq('id', existing.id);
      nameUpdated = true;
    }
    return {
      userId: existing.id,
      userName: nameUpdated ? contractorName! : (existing.name || email),
      wasCreated: false,
      nameUpdated,
    };
  }

  // Derive best name for new user
  const guessedName = looksLikeRealName(contractorName)
    ? contractorName!
    : email.split('@')[0]
        .replace(/[._\-]/g, ' ')
        .replace(/\b\w/g, (c: string) => c.toUpperCase());

  const tempPassword = generatePassword(12);

  const { data: authUser, error: authErr } = await supabase.auth.admin.createUser({
    email: email.toLowerCase(),
    password: tempPassword,
    email_confirm: true,
  });

  if (authErr || !authUser?.user) {
    throw new Error(`Auth creation failed for ${email}: ${authErr?.message}`);
  }

  const { error: profileErr } = await supabase.from('profiles').insert({
    id:                authUser.user.id,
    email:             email.toLowerCase(),
    username:          email.toLowerCase(),
    name:              guessedName,
    role:              'timesheetuser',
    manager_id:        null,
    country:           'US',
    region:            '',
    invoice_enabled:   false,
    imported_password: tempPassword,
  });

  if (profileErr) {
    await supabase.auth.admin.deleteUser(authUser.user.id);
    throw new Error(`Profile creation failed for ${email}: ${profileErr.message}`);
  }

  return { userId: authUser.user.id, userName: guessedName, wasCreated: true, nameUpdated: false };
}

// ─── Timesheet upsert with correction logic ───────────────────────────────────

async function upsertTimesheet(
  userId: string,
  userName: string,
  weekStart: string,
  entries: Record<string, number>,
  total: number,
  supabase: ReturnType<typeof createClient>
): Promise<{
  timesheetId: number | null;
  action: 'created' | 'updated' | 'correction_imported' | 'correction_pending';
  notes: string;
}> {
  const { data: existing } = await supabase
    .from('timesheets')
    .select('id, source, status')
    .eq('user_id', userId)
    .eq('week_start', weekStart)
    .maybeSingle();

  // ── Rule 1: Native submission exists → never overwrite ────────────────────
  if (existing?.source === 'direct') {
    return {
      timesheetId: existing.id,
      action: 'correction_pending',
      notes: 'Native submission exists — emailed correction flagged for admin review',
    };
  }

  // ── Rule 2: Imported timesheet exists → correction, needs review ──────────
  if (existing?.source === 'imported') {
    await supabase.from('timesheets').update({
      entries,
      status:      'pending',   // back to pending — needs manager review
      approved_by: null,
      approved_at: null,
      submitted_at: new Date().toISOString(),
    }).eq('id', existing.id);
    return {
      timesheetId: existing.id,
      action: 'correction_imported',
      notes: 'Correction received — reset to pending for manager review',
    };
  }

  // ── Rule 3: No existing record → create as auto-approved ─────────────────
  const record = {
    user_id:      userId,
    user_name:    userName,
    week_start:   weekStart,
    entries,
    status:       'approved',
    approved_by:  'system-import',
    approved_at:  new Date().toISOString(),
    source:       'imported',
    submitted_at: new Date().toISOString(),
  };

  const { data: inserted } = await supabase
    .from('timesheets').insert(record).select('id').single();

  return {
    timesheetId: inserted?.id ?? null,
    action: 'created',
    notes: 'Created and auto-approved',
  };
}

// ─── Main handler ─────────────────────────────────────────────────────────────

serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });

  // ── Auth ──────────────────────────────────────────────────────────────────
  const ingestSecret = Deno.env.get('INGEST_SECRET');
  const provided     = req.headers.get('x-ingest-secret');
  if (!ingestSecret || provided !== ingestSecret) {
    return new Response(JSON.stringify({ error: 'Unauthorized' }), {
      status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  const supabase = createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
  );

  let body: Record<string, unknown>;
  try { body = await req.json(); }
  catch {
    return new Response(JSON.stringify({ error: 'Invalid JSON' }), {
      status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  const {
    messageId,
    contractorEmail,
    contractorName,
    subject,
    weekStart,
    entries,
    total,
    attachmentName,
    attachmentType,
    parseNotes,
  } = body as Record<string, unknown>;

  if (!messageId || !contractorEmail || !weekStart) {
    return new Response(JSON.stringify({ error: 'Missing: messageId, contractorEmail, weekStart' }), {
      status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  // ── Deduplication ─────────────────────────────────────────────────────────
  // Allow reprocessing of partials (parser may have improved)
  // Block only on successfully processed messages
  const { data: existingLog } = await supabase
    .from('email_import_log')
    .select('id, parse_status, attempt_count')
    .eq('message_id', messageId as string)
    .maybeSingle();

  if (existingLog) {
    // Already successfully processed — true duplicate
    if (existingLog.parse_status === 'success' || existingLog.parse_status === 'duplicate') {
      return new Response(JSON.stringify({
        ok: true,
        action: 'duplicate',
        message: 'Already processed',
        existingStatus: existingLog.parse_status,
      }), { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
    }
    // Partial — delete old log entry so we can reprocess and create fresh entry
    // attempt_count will be incremented below
    await supabase.from('email_import_log').delete().eq('id', existingLog.id);
  }

  // Track attempt count for retry monitoring
  const attemptCount = existingLog ? (existingLog.attempt_count || 1) + 1 : 1;

  // ── Find or create user ───────────────────────────────────────────────────
  let userId: string;
  let userName: string;
  let wasCreated: boolean;
  let nameUpdated: boolean;

  try {
    ({ userId, userName, wasCreated, nameUpdated } = await findOrCreateUser(
      contractorEmail as string,
      contractorName as string | null,
      supabase
    ));
  } catch (e) {
    await supabase.from('email_import_log').insert({
      message_id:      messageId,
      from_email:      contractorEmail,
      resolved_email:  contractorEmail,
      subject,
      attachment_name: attachmentName || null,
      parse_status:    'failed',
      parse_notes:     `User error: ${String(e)}`,
    });
    return new Response(JSON.stringify({ ok: false, error: String(e) }), {
      status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  // ── Upsert timesheet ──────────────────────────────────────────────────────
  let timesheetId: number | null = null;
  let action = 'none';
  let upsertNotes = '';
  let parseStatus = 'success';

  if (entries && weekStart) {
    try {
      const parsedEntries = typeof entries === 'string' ? JSON.parse(entries as string) : entries;
      const parsedTotal   = Number(total) || 0;
      const result = await upsertTimesheet(
        userId, userName, weekStart as string,
        parsedEntries as Record<string, number>, parsedTotal, supabase
      );
      timesheetId  = result.timesheetId;
      action       = result.action;
      upsertNotes  = result.notes;

      if (action === 'correction_pending') parseStatus = 'correction_pending';
      else if (action === 'correction_imported') parseStatus = 'correction';
    } catch (e) {
      parseStatus = 'failed';
      upsertNotes = `Upsert error: ${String(e)}`;
    }
  } else {
    parseStatus = 'partial';
    upsertNotes = 'No hours parsed from attachment';
  }

  // ── Log ───────────────────────────────────────────────────────────────────
  await supabase.from('email_import_log').insert({
    message_id:      messageId,
    from_email:      contractorEmail,
    resolved_email:  contractorEmail,
    subject:         subject || null,
    attachment_name: attachmentName || null,
    parse_status:    parseStatus,
    parse_notes:     [parseNotes, upsertNotes].filter(Boolean).join(' | '),
    user_id:         userId,
    user_created:    wasCreated,
    timesheet_id:    timesheetId,
    week_start:      weekStart || null,
    raw_hours:       entries
      ? (typeof entries === 'string' ? JSON.parse(entries as string) : entries)
      : null,
    attempt_count:   attemptCount,
  });

  return new Response(JSON.stringify({
    ok:           true,
    action,
    parseStatus,
    userId,
    userName,
    wasCreated,
    nameUpdated,
    timesheetId,
    weekStart,
    notes:        upsertNotes,
    attemptCount,
  }), { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
});
