// Supabase Edge Function: ingest-timesheet
//
// Receives parsed timesheet data from the Node.js poller via HTTP POST.
// Handles: deduplication, user find-or-create, name improvement,
// timesheet upsert, correction detection, import logging.
//
// Correction rules:
//   - source='direct' exists → never overwrite, log as correction_pending
//   - source='imported' exists → update hours, keep auto-approved (trusted import channel)
//   - no existing record → create as approved (auto-approved on import)
//
// Auth: shared secret via x-ingest-secret header. JWT verification DISABLED.

import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-ingest-secret',
};

// ─── Helpers ──────────────────────────────────────────────────────────────────

// Detect if a stored name looks auto-generated from email prefix (worth replacing)
function sanitizeName(name: string | null): string | null {
  if (!name) return null;
  const cleaned = name.normalize('NFC').replace(/[\x00-\x1F\x7F-\x9F]/g, '').replace(/\s+/g, ' ').trim();
  return cleaned || null;
}

function isAutoGeneratedName(name: string | null, email: string): boolean {
  if (!name) return true;
  const prefix = email.split('@')[0].toLowerCase();
  const nameLower = name.toLowerCase().replace(/\s/g, '');
  if (nameLower === prefix) return true;           // exact email prefix match
  if (!name.includes(' ')) return true;            // single word = likely auto-generated
  if (name === name.toLowerCase()) return true;    // all lowercase
  if (name === name.toUpperCase()) return true;    // all uppercase
  return false;
}

function looksLikeRealName(name: string | null): boolean {
  if (!name) return false;
  return name.includes(' ') && name.length > 3 && name.length < 60 && !/^\d/.test(name);
}

// ─── User management ──────────────────────────────────────────────────────────
// Auto-creation is intentionally disabled. Users must be created by an admin
// before their timesheets can be ingested. Unknown emails are rejected here
// (the poller also blocks them at Layer 1, but this is a hard backstop).

async function findUser(
  email: string,
  contractorName: string | null,
  supabase: ReturnType<typeof createClient>
): Promise<{ userId: string; userName: string; nameUpdated: boolean } | null> {

  contractorName = sanitizeName(contractorName);

  const { data: existing } = await supabase
    .from('profiles')
    .select('id, name')
    .eq('email', email.toLowerCase())
    .maybeSingle();

  if (!existing) return null;

  let nameUpdated = false;
  if (looksLikeRealName(contractorName) && isAutoGeneratedName(existing.name, email)) {
    await supabase
      .from('profiles')
      .update({ name: contractorName })
      .eq('id', existing.id);
    nameUpdated = true;
  }
  return {
    userId: existing.id,
    userName: nameUpdated ? contractorName! : (existing.name || email),
    nameUpdated,
  };
}

// ─── Entry merge ─────────────────────────────────────────────────────────────
// When a contractor sends split timesheets for the same week (e.g. Apr 27-30 in
// one email, May 1 in another), take the max hours per day so partial submissions
// don't zero out days already recorded by an earlier email.
function mergeEntries(
  existing: Record<string, number>,
  incoming: Record<string, number>,
): Record<string, number> {
  const merged: Record<string, number> = { ...existing };
  for (const [day, hours] of Object.entries(incoming)) {
    const h = Number(hours) || 0;
    merged[day] = Math.max(Number(merged[day]) || 0, h);
  }
  return merged;
}

// ─── Week resolution ──────────────────────────────────────────────────────────
// Picks the best week from content-derived and subject-derived candidates.
// Decision order:
//   1. Discard anything more than 7 days in the future (parser artefact).
//   2. Single valid candidate → use it.
//   3. Correction keyword in email → content week wins (intentional re-submission).
//   4. One week is empty, the other occupied → prefer the empty week (new beats stale).
//   5. Both empty or both occupied → content week (index 0) wins as tiebreak.

async function resolveWeek(
  weekCandidates: string[],
  correctionHint: boolean,
  userId: string,
  supabase: ReturnType<typeof createClient>,
): Promise<{ resolvedWeek: string; resolutionNote: string | null }> {
  const now = Date.now();
  const SEVEN_DAYS_MS = 7 * 86400000;

  const valid = weekCandidates.filter(w => {
    const t = new Date(w + 'T12:00:00Z').getTime();
    return !isNaN(t) && t <= now + SEVEN_DAYS_MS;
  });
  const unique = [...new Set(valid)];

  if (unique.length <= 1) {
    const discarded = weekCandidates.length > unique.length;
    return {
      resolvedWeek: unique[0] ?? weekCandidates[0],
      resolutionNote: discarded ? `future candidate discarded; using ${unique[0] ?? weekCandidates[0]}` : null,
    };
  }

  const [weekA, weekB] = unique; // weekA = content, weekB = subject

  if (correctionHint) {
    return { resolvedWeek: weekA, resolutionNote: `correction keyword → content week ${weekA} (subject had ${weekB})` };
  }

  const { data: existing } = await supabase
    .from('timesheets')
    .select('week_start')
    .eq('user_id', userId)
    .in('week_start', unique);

  const occupied = new Set((existing ?? []).map((r: { week_start: string }) => r.week_start));

  if (!occupied.has(weekA) && occupied.has(weekB)) {
    return { resolvedWeek: weekA, resolutionNote: `content week ${weekA} empty, subject ${weekB} occupied → new submission` };
  }
  if (occupied.has(weekA) && !occupied.has(weekB)) {
    return { resolvedWeek: weekB, resolutionNote: `content week ${weekA} occupied, subject week ${weekB} empty → using subject week` };
  }

  const bothOccupied = occupied.has(weekA) && occupied.has(weekB);
  return {
    resolvedWeek: weekA,
    resolutionNote: bothOccupied
      ? `both weeks occupied → correction for content week ${weekA}`
      : `both weeks empty → content week ${weekA}`,
  };
}

// ─── Timesheet upsert with correction logic ───────────────────────────────────

async function upsertTimesheet(
  userId: string,
  userName: string,
  weekStart: string,
  entries: Record<string, number>,
  total: number,
  supabase: ReturnType<typeof createClient>,
  forwardedBy: string | null = null,
): Promise<{
  timesheetId: number | null;
  action: 'created' | 'updated' | 'correction_imported' | 'correction_pending';
  notes: string;
}> {
  const { data: existing } = await supabase
    .from('timesheets')
    .select('id, source, status, entries')
    .eq('user_id', userId)
    .eq('week_start', weekStart)
    .maybeSingle();

  // ── Rule 1: Native submission exists ─────────────────────────────────────
  // Internal forwarders (accountants) have authority to override portal submissions.
  // Only flag correction_pending when the email comes from the contractor themselves.
  if (existing?.source === 'direct') {
    if (!forwardedBy) {
      return {
        timesheetId: existing.id,
        action: 'correction_pending',
        notes: 'Native submission exists — emailed correction flagged for admin review',
      };
    }
    // Internal forwarder — apply correction as authoritative (hours may go up or down)
    await supabase.from('timesheets').update({
      entries,
      status:       'approved',
      approved_by:  'system-import',
      approved_at:  new Date().toISOString(),
      submitted_at: new Date().toISOString(),
    }).eq('id', existing.id);
    return {
      timesheetId: existing.id,
      action: 'correction_imported',
      notes: `Correction applied by internal forwarder (${forwardedBy}) — auto-approved`,
    };
  }

  // ── Rule 2: Imported timesheet exists → merge and keep auto-approved ───────
  // Merge entries (max per day) so partial-week submissions (e.g. month-end splits)
  // don't zero out days already recorded by an earlier email for the same week.
  if (existing?.source === 'imported') {
    const mergedEntries = mergeEntries(existing.entries as Record<string, number> || {}, entries);
    await supabase.from('timesheets').update({
      entries:      mergedEntries,
      status:       'approved',
      approved_by:  'system-import',
      approved_at:  new Date().toISOString(),
      submitted_at: new Date().toISOString(),
    }).eq('id', existing.id);
    return {
      timesheetId: existing.id,
      action: 'correction_imported',
      notes: 'Correction received — auto-approved (imported source)',
    };
  }

  // ── Rule 3: No existing record → create as auto-approved ─────────────────
  const record = {
    user_id:      userId,
    user_name:    userName,
    week_start:   weekStart,
    entries,
    status:       'approved',
    approved_by:  'system-import',
    approved_at:  new Date().toISOString(),
    source:       'imported',
    submitted_at: new Date().toISOString(),
  };

  const { data: inserted } = await supabase
    .from('timesheets').insert(record).select('id').single();

  return {
    timesheetId: inserted?.id ?? null,
    action: 'created',
    notes: 'Created and auto-approved',
  };
}

// ─── Main handler ─────────────────────────────────────────────────────────────

serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });

  // ── Auth ──────────────────────────────────────────────────────────────────
  const ingestSecret = Deno.env.get('INGEST_SECRET');
  const provided     = req.headers.get('x-ingest-secret');
  if (!ingestSecret || provided !== ingestSecret) {
    return new Response(JSON.stringify({ error: 'Unauthorized' }), {
      status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  const supabase = createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
  );

  let body: Record<string, unknown>;
  try { body = await req.json(); }
  catch {
    return new Response(JSON.stringify({ error: 'Invalid JSON' }), {
      status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  // ── Log-only mode — unsupported attachment types logged by poller ────────────
  if (body.logOnly === true) {
    const { messageId: lMsgId, contractorEmail: lEmail, attachmentName: lAtt, parseNotes: lNotes, subject: lSubject, run_id: lRunId } = body;
    if (!lMsgId) {
      return new Response(JSON.stringify({ error: 'Missing messageId' }), {
        status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }
    const { data: existing } = await supabase.from('email_import_log').select('id').eq('message_id', lMsgId as string).maybeSingle();
    if (existing) {
      return new Response(JSON.stringify({ ok: true, action: 'duplicate' }), { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
    }
    await supabase.from('email_import_log').insert({
      message_id:      lMsgId,
      from_email:      lEmail || null,
      resolved_email:  lEmail || null,
      subject:         lSubject || null,
      attachment_name: lAtt || null,
      parse_status:    'failed',
      parse_notes:     lNotes || 'Unsupported file type',
      run_id:          lRunId || null,
    });
    return new Response(JSON.stringify({ ok: true, action: 'logged_skip' }), { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
  }

  const {
    messageId,
    contractorEmail,
    contractorName,
    subject,
    weekStart,
    weekCandidates,
    correctionHint,
    entries,
    total,
    attachmentName,
    attachmentType,
    parseNotes,
    run_id,
    forwardedBy,
  } = body as Record<string, unknown>;

  if (!messageId || !contractorEmail || !weekStart) {
    return new Response(JSON.stringify({ error: 'Missing: messageId, contractorEmail, weekStart' }), {
      status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  // ── Deduplication ─────────────────────────────────────────────────────────
  // Allow reprocessing of partials (parser may have improved)
  // Block only on successfully processed messages
  const { data: existingLog } = await supabase
    .from('email_import_log')
    .select('id, parse_status, attempt_count')
    .eq('message_id', messageId as string)
    .maybeSingle();

  if (existingLog) {
    // Already handled — don't reprocess.
    // 'success', 'duplicate'          → created or already deduped
    // 'correction', 'correction_pending' → correction was applied; re-running would
    //   delete this log entry and apply another correction on every poller run forever.
    const DONE_STATUSES = ['success', 'duplicate', 'correction', 'correction_pending'];
    if (DONE_STATUSES.includes(existingLog.parse_status)) {
      return new Response(JSON.stringify({
        ok: true,
        action: 'duplicate',
        message: 'Already processed',
        existingStatus: existingLog.parse_status,
      }), { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
    }
    // Partial / failed — delete old log entry so we can reprocess and create fresh entry
    // attempt_count will be incremented below
    await supabase.from('email_import_log').delete().eq('id', existingLog.id);
  }

  // Track attempt count for retry monitoring
  const attemptCount = existingLog ? (existingLog.attempt_count || 1) + 1 : 1;

  // ── Find user (no auto-creation) ─────────────────────────────────────────
  let userId: string;
  let userName: string;
  const wasCreated = false;
  let nameUpdated: boolean;

  try {
    const found = await findUser(
      contractorEmail as string,
      contractorName as string | null,
      supabase
    );
    if (!found) {
      await supabase.from('email_import_log').insert({
        message_id:      messageId,
        from_email:      contractorEmail,
        resolved_email:  contractorEmail,
        subject,
        attachment_name: attachmentName || null,
        parse_status:    'failed',
        parse_notes:     'Unknown contractor — not in profiles. Add user via admin panel first.',
        attempt_count:   attemptCount,
        run_id:          run_id || null,
      });
      return new Response(JSON.stringify({ ok: false, error: 'unknown_contractor' }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }
    ({ userId, userName, nameUpdated } = found);
  } catch (e) {
    await supabase.from('email_import_log').insert({
      message_id:      messageId,
      from_email:      contractorEmail,
      resolved_email:  contractorEmail,
      subject,
      attachment_name: attachmentName || null,
      parse_status:    'failed',
      parse_notes:     `User lookup error: ${String(e)}`,
      run_id:          run_id || null,
    });
    return new Response(JSON.stringify({ ok: false, error: String(e) }), {
      status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  // ── Resolve week from candidates ──────────────────────────────────────────
  // weekCandidates[0] = content-derived, [1] = subject-derived (when they differ).
  // Falls back to weekStart if candidates not supplied (older poller versions).
  let resolvedWeek = weekStart as string;
  let resolutionNote: string | null = null;
  const candidates = Array.isArray(weekCandidates) && weekCandidates.length > 0
    ? weekCandidates as string[]
    : [weekStart as string].filter(Boolean);

  if (candidates.length > 0 && entries) {
    const resolved = await resolveWeek(candidates, !!correctionHint, userId, supabase);
    resolvedWeek   = resolved.resolvedWeek;
    resolutionNote = resolved.resolutionNote;
    if (resolutionNote) console.log(`  🗓️  Week resolved: ${resolutionNote}`);
  }

  // ── Upsert timesheet ──────────────────────────────────────────────────────
  let timesheetId: number | null = null;
  let action = 'none';
  let upsertNotes = '';
  let parseStatus = 'success';

  if (entries && resolvedWeek) {
    try {
      const parsedEntries = typeof entries === 'string' ? JSON.parse(entries as string) : entries;
      const parsedTotal   = Number(total) || 0;
      const result = await upsertTimesheet(
        userId, userName, resolvedWeek,
        parsedEntries as Record<string, number>, parsedTotal, supabase,
        (forwardedBy as string) || null,
      );
      timesheetId  = result.timesheetId;
      action       = result.action;
      upsertNotes  = result.notes;

      if (action === 'correction_pending') parseStatus = 'correction_pending';
      else if (action === 'correction_imported') parseStatus = 'correction';
    } catch (e) {
      parseStatus = 'failed';
      upsertNotes = `Upsert error: ${String(e)}`;
    }
  } else {
    parseStatus = 'partial';
    upsertNotes = 'No hours parsed from attachment';
  }

  // ── Log ───────────────────────────────────────────────────────────────────
  await supabase.from('email_import_log').insert({
    message_id:      messageId,
    from_email:      contractorEmail,
    resolved_email:  contractorEmail,
    subject:         subject || null,
    attachment_name: attachmentName || null,
    parse_status:    parseStatus,
    parse_notes:     [parseNotes, upsertNotes, resolutionNote].filter(Boolean).join(' | '),
    user_id:         userId,
    user_created:    wasCreated,
    timesheet_id:    timesheetId,
    week_start:      resolvedWeek || weekStart || null,
    raw_hours:       entries
      ? (typeof entries === 'string' ? JSON.parse(entries as string) : entries)
      : null,
    attempt_count:   attemptCount,
    run_id:          run_id || null,
  });

  return new Response(JSON.stringify({
    ok:           true,
    action,
    parseStatus,
    userId,
    userName,
    wasCreated,
    nameUpdated,
    timesheetId,
    weekStart:    resolvedWeek,
    notes:        upsertNotes,
    attemptCount,
  }), { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
});
